# Generated by Django 5.2 on 2025-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('university', models.CharField(max_length=40)),
                ('passing_year', models.DateField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('teacher_id', models.IntegerField()),
                ('picture', models.ImageField(upload_to='profile/')),
                ('email', models.EmailField(max_length=254)),
                ('degree', models.ManyToManyField(to='teacher.degree')),
            ],
        ),
    ]
