# Generated by Django 5.2.1 on 2025-07-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_degree_degree_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
