# Generated by Django 5.2.1 on 2025-07-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_permanent_address_teacher_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('university', models.CharField(max_length=40)),
                ('passing_year', models.DateField()),
                ('result', models.CharField(max_length=10)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='teacher.teacher')),
            ],
        ),
    ]
