# Generated by Django 5.2.1 on 2025-05-28 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0004_remove_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
