# Generated by Django 5.2.1 on 2025-05-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_part_teacher'),
        ('teacher', '0004_remove_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
