# Generated by Django 5.2.1 on 2025-07-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_classsession_attendancerecord_classtest_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='classtest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='time',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='topic',
        ),
    ]
