# Generated by Django 5.2.1 on 2025-07-09 09:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_classtest_date_remove_classtest_time_and_more'),
        ('student', '0002_student_previous_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='part',
        ),
        migrations.RemoveField(
            model_name='classtest',
            name='part',
        ),
        migrations.RemoveField(
            model_name='testmark',
            name='test',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='exammark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testmark',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.part')),
            ],
            options={
                'ordering': ['-date', '-class_number'],
                'unique_together': {('part', 'class_number')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='P', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.class')),
            ],
            options={
                'unique_together': {('class_session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_number', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=200, null=True)),
                ('total_marks', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.part')),
            ],
            options={
                'ordering': ['-date', '-ct_number'],
                'unique_together': {('part', 'ct_number')},
            },
        ),
        migrations.CreateModel(
            name='CTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.ct')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('ct', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
        migrations.DeleteModel(
            name='ClassTest',
        ),
        migrations.DeleteModel(
            name='ExamMark',
        ),
        migrations.DeleteModel(
            name='TestMark',
        ),
    ]
