# Generated by Django 5.2.1 on 2025-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_todo_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('done', 'Done')], default='upcoming', max_length=10),
        ),
    ]
