# Generated by Django 5.2.1 on 2025-06-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='teacher',
        ),
    ]
