# Generated by Django 5.2.1 on 2025-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_previous_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
